name: Functions Tests

on: [push]

jobs:
  pytest_workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install database
        run: |
          sudo apt install --yes --no-install-recommends postgresql postgresql-contrib
          sudo systemctl start postgresql.service
          psql -h localhost -U postgres -c "CREATE USER pi WITH PASSWORD 'pi';"
          psql -h localhost -U postgres -c " CREATE DATABASE test_task_manager;"
          psql -h localhost -U postgres -c " GRANT ALL on test_task_manager to pi;"
      - name: Test with pytest
        run: |
          pytest
