name: Functions Tests

on: [push]

jobs:
  pytest_workflow:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:10-2.5
        env:
          # must specify password for PG Docker container image, see: https://registry.hub.docker.com/_/postgres?tab=description&page=1&name=10
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_task_manager
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build postgres tables and users
        run: |
          psql -h postgres -U "CREATE USER pi WITH PASSWORD 'pi';"
          psql -h postgres -U "CREATE DATABASE test_task_manager;"
          psql -h postgres -U "GRANT ALL on test_task_manager to pi;"
        env:
          PGPASSWORD: password

      - name: Test with pytest
        run: |
          pytest
        env:
          CI_DB_URL: postgresql://postgres:password@localhost:5432/test_task_manager
